FROM nginx:stable-alpine

# Copy website files
COPY . /usr/share/nginx/html

# Copy custom nginx config (HTTP only for CI)
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/ci-http.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
