import express from 'express';
import dotenv from 'dotenv';
import nodemailer from 'nodemailer';
import { renderQuoteRequestPdf } from './src/quote/renderQuoteRequestPdf.js';
import { mapToQuoteRequestView } from './src/quote/mapToQuoteRequestView.js';

dotenv.config();

const app = express();
app.use(express.json());

// Basic validation helpers
const isEmail = (v) => /.+@.+\..+/.test(v || "");
const isNonEmpty = (v) => typeof v === 'string' && v.trim().length > 0;

// Transport
function createTransport() { 
  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT || 465);
  const secure = String(process.env.SMTP_SECURE || 'true').toLowerCase() === 'true';
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !user || !pass) {
    throw new Error('SMTP configuration missing. Set SMTP_HOST, SMTP_USER, SMTP_PASS.');
  }

  console.log(`[SMTP] Connecting to ${host}:${port} with user: ${user} (secure: ${secure})`);
  const transport = nodemailer.createTransport({ host, port, secure, auth: { user, pass } });
  
  // Verify connection configuration
  transport.verify(function(error, success) {
    if (error) {
      console.log('[SMTP] Verification failed:', error);
    } else {
      console.log('[SMTP] Server is ready to send messages');
    }
  });
  
  return transport;
}

function buildHtmlBody(payload) {
  const rows = [
    ['Name', payload.name],
    ['Email', payload.email],
    ['Phone', payload.phone],
    ['Product category', payload.productCategory],
    ['Delivery timeline', payload.deliveryDate],
    ['Estimated quantity', payload.estimatedQuantity || '—'],
    ['Order details', payload.orderDetails]
  ];

  const tableRows = rows.map(([label, value]) => `
    <tr>
      <td style="padding:8px;border:1px solid #e5e7eb;font-weight:600;color:#111827">${label}</td>
      <td style="padding:8px;border:1px solid #e5e7eb;color:#374151">${String(value).replace(/</g,'&lt;')}</td>
    </tr>`).join('');

  return `
  <div style="font-family:Arial,Helvetica,sans-serif;color:#111827">
    <h2 style="margin:0 0 12px 0;color:#14529d">New Quote Request</h2>
    <p style="margin:0 0 16px 0;color:#374151">Leetshego Safety Solutions</p>
    <table style="border-collapse:collapse;width:100%;max-width:720px">${tableRows}</table>
    <p style="margin-top:16px;color:#6b7280;font-size:12px">This email was generated by the website quote form.</p>
  </div>`;
}


app.post('/quote-request', async (req, res) => {
  const {
    name,
    email,
    phone,
    productCategory,
    deliveryDate,
    estimatedQuantity,
    orderDetails
  } = req.body || {};

  // Validate
  const errors = [];
  if (!isNonEmpty(name)) errors.push('name');
  if (!isEmail(email)) errors.push('email');
  if (!isNonEmpty(phone)) errors.push('phone');
  if (!isNonEmpty(productCategory)) errors.push('productCategory');
  if (!isNonEmpty(orderDetails)) errors.push('orderDetails');
  // deliveryDate optional but recommended

  if (errors.length) {
    return res.status(400).json({ ok: false, error: 'validation', fields: errors });
  }

  const payload = {
    name: name.trim(),
    email: email.trim(),
    phone: phone.trim(),
    productCategory: productCategory.trim(),
    deliveryDate: (deliveryDate || '').toString().trim(),
    estimatedQuantity: (estimatedQuantity || '').toString().trim(),
    orderDetails: orderDetails.trim()
  };

  try {
    const transporter = createTransport();
    const toAddress = process.env.TO_EMAIL || 'Leetshegoss@gmail.com';
    const fromAddress = process.env.FROM_EMAIL || process.env.SMTP_USER;
    const subject = `New quote request from ${payload.name} – Leetshego Safety Solutions`;
    const html = buildHtmlBody(payload);

    // Try PDF
    let attachments = [];
    try {
      const ts = new Date();
      const yyyyMMdd = ts.toISOString().slice(0,10).replace(/-/g,'');
      const hhmm = String(ts.getHours()).padStart(2,'0') + String(ts.getMinutes()).padStart(2,'0');
      const pdfName = `quote-request-${yyyyMMdd}-${hhmm}-${payload.name.replace(/\s+/g,'_')}.pdf`;
      const view = mapToQuoteRequestView(payload);
      const pdfBuffer = await renderQuoteRequestPdf(view);
      attachments.push({ filename: pdfName, content: pdfBuffer, contentType: 'application/pdf' });
    } catch (pdfErr) {
      // Continue without PDF
    }

    await transporter.sendMail({
      from: fromAddress,
      to: toAddress,
      subject,
      html,
      attachments
    });

    return res.json({ ok: true });
  } catch (err) {
    console.error('Email send error', err);
    return res.status(500).json({ ok: false, error: 'server' });
  }
});

const PORT = Number(process.env.PORT || 3000);
app.listen(PORT, () => {
  console.log(`Quote API listening on port ${PORT}`);
});
